name: Build Iosevka

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ttfautohint

      - name: Install npm deps
        run: npm install

      - name: Build font
        run: |
          npm run build -- contents::iosevka-custom

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iosevka-font
          path: dist/**
